### PR TITLE
Use incremental loader in container_test

### PR DESCRIPTION
**Pull request by scele**
When using the docker driver to run container_tests, use the
fast incremental loader instead of "docker loading" the tarball.
Producing the tarball can be very expensive for large images.

Also rewrite container_test runfiles assembly to avoid calls to
depset.to_list().

### CODE REVIEW

**Comment by xingao267** [comment]
@scele thanks for the PR. Could you update existing container_test targets in this repo?

**Comment by xingao267** [comment]
It looks like it breaks the existing container_test targets in bazel-toolchains repo https://buildkite.com/bazel/bazel-toolchains/builds/1096#5923b00f-ddaa-480e-8658-57b70212d338

**Comment by xingao267** [comment]
But it's possible that the rule in bazel-toolchains needs a fix. Still looking.

**Comment by xingao267** [comment]
It looks like it's because we are missing the legacy base tarball in the runfiles so the loader cannot load the base.

**Comment by xingao267** [comment]
It's the container_bundle that doesn't prepare the runfiles properly. I sent https://github.com/bazelbuild/rules_docker/pull/645

**Comment by scele** [comment]
Thanks for root causing and fixing the issue! :)

**Pull request merged**
