### PR TITLE
Allow container_layer's data_path to work on directory output target names

### PR DESCRIPTION
**Pull request by EdSchouten**
There is a tiny bug in pkg_tar's strip_prefix handling that prevents it
from stripping the full name of a file. Though this sounds weird at
first, it is pretty useful when creating tarballs from output
directories. A pull request for this has been sent to Bazel:

https://github.com/bazelbuild/bazel/pull/6980

The same issue applies to container_layer's data_path argument, which is
actually where we noticed this at first. Also apply this fix here.

### CODE REVIEW

**Comment by xingao267** [comment]
@EdSchouten, thanks for the PR. Could you make a simple test for this?

**Comment by EdSchouten** [comment]
> @EdSchouten, thanks for the PR. Could you make a simple test for this?

Done!

**Comment by nlopezgi** [comment]
Thanks for adding the tests. Looks good. Will kick off Buildkite tests, but travis CI failed due to buildifier.
Can you run buildifier on ./tests/docker/BUILD

**Comment by nlopezgi** [comment]
Thanks again, one question though, 
Do we need to update anything in the README after this PR is in? Specifically, does this PR change the statement in this section (https://github.com/bazelbuild/rules_docker/#container_image) - the bit that starts with "Hint: ..." ?

**Comment by EdSchouten** [comment]
Hi there,

> Thanks again, one question though,

And thank you for merging this so quickly!

> Do we need to update anything in the README after this PR is in? Specifically, does this PR change the statement in this section (https://github.com/bazelbuild/rules_docker/#container_image) - the bit that starts with "Hint: ..." ?

I think that part of the documentation remains unaffected. It's just that archiving of directory outputs and stripping prefixes already worked, except when they were combined and stripped the entire path prefix.

**Pull request merged**
