### PR TITLE
Remove python entrypoint declarations 

### PR DESCRIPTION
**Pull request by mmikitka**
See issue https://github.com/bazelbuild/rules_docker/issues/1247

### CODE REVIEW

**Comment by nlopezgi** [comment]
Test py_image_complex_layer is failing, can you double check it please

**Comment by mmikitka** [comment]
I'm seeing the following failure, and the cause is not obvious to me:
```
FAILURE: Expected 'Calling from main module: through py_image_complex_library: Six version: 1.11.0' not found in 'Loaded image ID: sha256:164cea6a3df2588b416bf8393f9a03897e9446eb49ee0f4e7af7ee104c2eebbe

**Comment by mmikitka** [comment]
Note that the py_binary is in the image entrypoint, and the error message `exec user process caused "no such file or directory"` is caused by the absence of `/usr/bin/env` on the system, as referenced in the shebang.

Relevant output of `docker inspect bazel/testdata:py_image_complex`:
```
           "Cmd": null,
            "WorkingDir": "/app/testdata/py_image_complex.binary.runfiles/io_bazel_rules_docker",
            "Entrypoint": [
                "/app/testdata/py_image_complex.binary"
            ],
```

The top of `/app/testdata/py_image_complex.binary` contains:
```
#!/usr/bin/env python
```

And, /usr/bin/env is not in the py_image_base layer.

Nonetheless, this is somewhat beside the point, as we don't want to assume that the Python interpreter resolved by `/usr/bin/env` is the same as the interpreter specified by the toolchain.

Essentially, we need the toolchain-specific Python interpreter to be the first command in the entrypoint.

**Comment by mmikitka** [comment]
Since we don't want language-specific logic (in this case Python) in the app_layer implementation, one solution is to remove the absolute path to Python, and rely on PATH resolution when calling python in the entrypoint.

**Comment by mmikitka** [comment]
@nlopezgi Can we require users to explicitly declare the entrypoint in the event that `which` is not available (e.g., distroless) or the python path cannot be resolved?

Either way, an assumption must be made of the underlying base image i.e., is `which` available or is `/usr/bin/python` available.

However, if you can propose a solution that does not require language-specific code in app_layer, I would gladly implement it.

**Comment by nlopezgi** [comment]
> @nlopezgi Can we require users to explicitly declare the entrypoint in the event that `which` is not available (e.g., distroless) or the python path cannot be resolved?
> 

no, that would break to many existing use cases

> Either way, an assumption must be made of the underlying base image i.e., is `which` available or is `/usr/bin/python` available.
> 

For now, we will assume the latter, as that is the way it's currently implemented.

> However, if you can propose a solution that does not require language-specific code in app_layer, I would gladly implement it.

I can't think of any. Would adding the symlink to /usr/bin/python in the base container be an acceptable workaround for you?

**Comment by mmikitka** [comment]
@nlopezgi I'll resort to explicitly setting the entrypoint or using a symlink as you suggested. Thanks for the conversation, and I think that we can close this issue

**Pull request closed without merging**
