### PR TITLE
Support airgapped environment

### PR DESCRIPTION
**Pull request by smartkiwi**
`go_repository` git `commit` doesn't support `http_load` caching mechanism thus prevents `rules_docker` to be used in air gapped environment.

Replacing it with alternative `urls` address makes go_repository to use `http_load` and utilize [caching mechanism](https://docs.bazel.build/versions/master/guide.html#running-bazel-in-an-airgapped-environment) if needed.
An additional piece of information will be needed in future for updating dependencies' versions - sha256.
One way to get sha256 on mac - to download the file from `https://codeload.github.com/<org>/<repo>/zip/<commit>` and running `shasum -a 256 <file>`

### CODE REVIEW

**Comment by smartkiwi** [comment]
@googlebot I signed it!

**Comment by smartkiwi** [comment]
Note: `buildifier repositories/go_repositories.bzl` run successfully on my mac os x on a modified version of file - and I cannot tell from buildkite build output - what it didn't like there

**Comment by smartkiwi** [comment]
@smukherj1 would you be able to help with reviewing this PR ?

**Review by smukherj1 — APPROVED** [review]
Looks ok given the tests pass. I think usually gzip compresses better than zip but maybe it won't make a huge difference for Go repos.

**Comment by smartkiwi** [comment]
> I think usually gzip compresses better than zip but maybe it won't make a huge difference for Go repos.
I'll change URLs to pull gzips - as you mentioned archive is 30% smaller - which is beneficial for airgapped usage scenario (the fewer bytes to download - the faster build will start).
I would also need to update sha256 to tag.gz files.
Would you please run tests again after update?
```
curl -L https://api.github.com/repos/google/go-containerregistry/zipball/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb > e5f4efd48dbff3ab3165a944d6777f8db28f0ccb.zip
curl -L https://api.github.com/repos/google/go-containerregistry/tarball/e5f4efd48dbff3ab3165a944d6777f8db28f0ccb > e5f4efd48dbff3ab3165a944d6777f8db28f0ccb.tar.gz
-rw-r--r--   1 user  staff   8154654 Sep 11 11:18 e5f4efd48dbff3ab3165a944d6777f8db28f0ccb.zip
-rw-r--r--   1 user  staff   5785281 Sep 11 11:18 e5f4efd48dbff3ab3165a944d6777f8db28f0ccb.tar.gz
```

**Comment by smukherj1** [comment]
Ok the other PR is merged. Let me know when this PR is ready to review again

**Comment by smartkiwi** [comment]
Had to close this PR because of last commit created from non existing github user
I copied changes here https://github.com/bazelbuild/rules_docker/pull/1619

**Pull request closed without merging**
