### PR TITLE
WIP: Reordering this dict somehow fixes !1872.

### PR DESCRIPTION
**Pull request by gravypod**
I need more time to debug this but more context is here:

  https://github.com/bazelbuild/rules_docker/issues/1872

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
we're missing some test coverage of course...

**Review by pcj — CHANGES_REQUESTED** [review]
I don't see how this would possibly fix a bug.  Is this reproducible?

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
@pcj the order of the outputs is totally a part of the public API and other rules can depend on it.

In this case I think https://github.com/bazelbuild/rules_docker/blob/master/container/layer_tools.bzl#L123 is the spot where this particular re-ordering broke it.

**Review by pcj — APPROVED** [review]
At a minimum this needs a comment as to the importance to preserving ordering here.

**Comment by pcj** [comment]
Merging this for #1872

**Pull request merged**
