### PR TITLE
py_image() and py3_image() now respect restricted_to and compatible_with

### PR DESCRIPTION
**Pull request by jondo2010**
Basically the same as #669

### CODE REVIEW

**Comment by xingao267** [comment]
Thanks for the PR. It looks good. Could you sign the CLA?

**Comment by jondo2010** [comment]
> Thanks for the PR. It looks good. Could you sign the CLA?

Thanks. I'm just waiting for my legal get back to me on the CLA.

**Comment by BenTheElder** [comment]
/hold
the lack of CLA and unmergable PR are interacting poorly with the merge robot (prow.k8s.io)
placing a hold to drop it off the merge robot https://prow.k8s.io/tide-history?repo=bazelbuild%2Frules_docker&branch=master

**Comment by nlopezgi** [comment]
hi @jondo2010,
did you get a chance to figure out about CLA? Otherwise can we close?

**Pull request closed without merging**
