### PR TITLE
Fix `rust_image`

### PR DESCRIPTION
**Pull request by UebelAndre**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/bazelbuild/rules_docker/issues/1949

## What is the new behavior?
Fixes https://github.com/bazelbuild/rules_docker/issues/1949

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
closes https://github.com/bazelbuild/rules_docker/issues/1949

### CODE REVIEW

**Comment by UebelAndre** [comment]
This PR is blocked by a series of failures unrelated to the changes here.
```
================================================================================
==================== Test output for //tests/container:alpine_custom_attr_digest_test:
/private/var/tmp/_bazel_buildkite/f9511fe9dd152becd17d41841444d68d/sandbox/darwin-sandbox/724/execroot/io_bazel_rules_docker/bazel-out/darwin-fastbuild/bin/tests/container/alpine_custom_attr_digest_test.runfiles/io_bazel_rules_docker/tests/container/alpine_custom_attr_digest_test_impl.sh.dat 2021-11-05 15:11:49.000000000 +0000
/private/var/tmp/_bazel_buildkite/f9511fe9dd152becd17d41841444d68d/sandbox/darwin-sandbox/724/execroot/io_bazel_rules_docker/bazel-out/darwin-fastbuild/bin/tests/container/alpine_custom_attr_digest_test.runfiles/io_bazel_rules_docker/tests/container/new_push_test_legacy_from_container_img.digest 2021-11-05 15:11:52.000000000 +0000
@@ -1 +1 @@
-sha256:2f3bf2d061a1bab130cdd98f10b73dfceb08bfbf94a610c62f20c787073e5178
\ No newline at end of file
+sha256:63a40621b30af05f51fb2b38c2b5c56f9cc82cc605d556e09cacdbbdc5adec63
\ No newline at end of file
```

**Comment by gravypod** [comment]
This change looks good but it looks like some things are failing on mac: 


```
//tests/container:alpine_custom_attr_digest_test
//tests/container:image_test
//tests/container:test_digest_output1
```

I don't know if your change effects these. Some other users have seen these issues with our CI (hashing failures on some targets). Would you mind trying to debug these to see if they're from your PR?

**Comment by UebelAndre** [comment]
They're not from my PR. The same failure occurs on https://github.com/bazelbuild/rules_docker/pull/1948

**Comment by UebelAndre** [comment]
Deleting in favor of https://github.com/bazelbuild/rules_docker/pull/1951

**Comment by dfreese** [comment]
> Deleting in favor of #1951

Whoops, didn't look to see if this had come up previously!

**Comment by UebelAndre** [comment]
> > Deleting in favor of #1951
> 
> 
> 
> Whoops, didn't look to see if this had come up previously!

All good buddy 😃 just so long as the changes go in, I don't care who's name is on the PR

**Pull request closed without merging**
