### PR TITLE
Add name attribute to override ctx.label.name.

### PR DESCRIPTION
**Pull request by xingao267**

### CODE REVIEW

**Comment by xingao267** [comment]
Not ready for review yet.

**Comment by xingao267** [comment]
@erain ready for review.

**Comment by xingao267** [comment]
Thanks. Will do when submitting the change.

**Comment by erain** [comment]
@xingao267 : it looks like this PR affect https://github.com/bazelbuild/rules_k8s/pull/130

We can talk more next week.

**Comment by xingao267** [comment]
@erain https://github.com/bazelbuild/rules_docker/commit/7228cb2764c519408478c70c6865090bdb856be7 changes the signature of get_from_target(). https://github.com/bazelbuild/rules_k8s/pull/130 should fix it.

**Comment by xingao267** [comment]
Commented in https://github.com/bazelbuild/rules_k8s/issues/125

**Pull request merged**
