### PR TITLE
[WIP] Add a Windows CI configuration

### PR DESCRIPTION
**Pull request by mattmoor**

### CODE REVIEW

**Comment by mattmoor** [comment]
@dslomov @meteorcloudy @laszlocsomor is looks like the `sha256` stuff we [bundle with Bazel](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/hash/sha256.py) suffers the same [issue I see](https://github.com/bazelbuild/rules_python/pull/6) in `rules_python` (the error there is in `google/subpar`).

```shell
ERROR: C:/temp/_bazel_system/3ystaro3/external/distroless_base/image/BUILD:6:1: SHA256 external/distroless_base/image/000.tar.gz.sha256 failed (Exit 1): sha256.exe failed: error executing command 
  cd C:/temp/_bazel_system/3ystaro3/execroot/io_bazel_rules_docker
bazel-out/host/bin/external/bazel_tools/tools/build_defs/hash/sha256.exe external/distroless_base/image/000.tar.gz bazel-out/msvc_x64-fastbuild/bin/external/distroless_base/image/000.tar.gz.sha256.
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site.py", line 570, in <module>
    main()
  File "C:\Program Files\Anaconda3\lib\site.py", line 561, in main
    os.environ["PATH"])
  File "C:\Program Files\Anaconda3\lib\os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
Failed to import the site module
```

**Comment by mattmoor** [comment]
@dslomov You'd indicated you had a fix/workaround for this.  Can you share? :D

**Comment by laszlocsomor** [comment]
@mattmoor : FYI Dmitry and most of the folks in MUC are out of office this week.

**Comment by mattmoor** [comment]
@laszlocsomor I know he's here!  He was telling me over coffee :)

**Comment by mattmoor** [comment]
@dslomov Wanted to bump this in case you had a solution?

**Pull request closed without merging**
