### PR TITLE
Add 'digest' field to PushInfo provider.

### PR DESCRIPTION
**Pull request by ceason**
This PR adds a 'digest' field to PushInfo provider. The field's value is a `<File>` containing the to-be-published image digest.

I rearranged the `container_pusher` implementation function a bit, to emphasize that the digester needs to receive the same arguments as the pusher.

### CODE REVIEW

**Comment by nlopezgi** [comment]
Also, please ignore the buildkite failures, there's an upstream issue with buildkite that is impacting all bazelbuild projects which should be fixed soon.

**Comment by nlopezgi** [comment]
created https://github.com/bazelbuild/rules_docker/pull/595 to add a test

**Comment by nlopezgi** [comment]
Test for `container_push` has been added, let me know if you need help setting up a test to validate your PR.

**Comment by nlopezgi** [comment]
Thanks, setting up the test should not be hard, let me know if you run into issues or have questions.

**Comment by ceason** [comment]
I've added a `file_test`. Thanks for the suggestion -- named output+file_test was definitely the easy path :)

**Pull request merged**
