### PR TITLE
chore: update rules_nodejs to latest

### PR DESCRIPTION
**Pull request by alexeagle**
Note that we are moving defs.bzl to index.bzl before our 1.0 release

### CODE REVIEW

**Comment by nlopezgi** [comment]
Hi @alexeagle 
This is failing on CI because `rules_nodejs` is pinned to an old version of bazel-toolchains and that declaration is overriding the one we have in this repo. The easies fix is for you to update to the latest release of bazel-toolchains (https://github.com/bazelbuild/bazel-toolchains/releases/tag/1.1.0). The alternative is to play around with the order of the declaration of `rules_nodejs` and `bazel_toolchains` in the `rules_docker` WORKSPACE (probably move `bazel_toolchains` to the top). Let me know which alternative you prefer.

**Comment by alexeagle** [comment]
Thanks, updating that in https://github.com/bazelbuild/rules_nodejs/pull/1302
then I guess we need a rules_nodejs release to bring the update here

**Comment by alexeagle** [comment]
Updated to a rules_nodejs release that has updated pinned bazel-toolchains

**Comment by nlopezgi** [comment]
This is failing with lots of errors like this one:

```
(15:30:23) ERROR: missing input file '@npm_deps//:node_modules/jsesc/LICENSE-MIT.txt'
--
  | (15:30:23) ERROR: missing input file '@npm_deps//:node_modules/jsesc/README.md'
  | (15:30:23) ERROR: missing input file '@npm_deps//:node_modules/jsesc/bin/jsesc'
  | (15:30:23) ERROR: missing input file '@npm_deps//:node_modules/jsesc/jsesc.js'
  | (15:30:23) ERROR: missing input file '@npm_deps//:node_modules/jsesc/man/jsesc.1'
  | (15:30:23) ERROR: missing input file '@npm_deps//:node_modules/jsesc/package.json'
  | (15:30:23) ERROR: missing input file '//tests/container/nodejs:io_bazel_rules_docker/testdata/nodejs_image.js'
```

Haven't looked in detail at the cause; maybe you know what the issue here is?

**Comment by nlopezgi** [comment]
subsumed by https://github.com/bazelbuild/rules_docker/pull/1324

**Pull request closed without merging**
