### PR TITLE
enable directory in py_image

### PR DESCRIPTION
**Pull request by justinwp**
Quick change without looking at the details. Not sure what you had envisioned but would like this functionality.

### CODE REVIEW

**Comment by erain** [comment]
Hi @justinwp : thanks for sending the PR and I think this is a valid change. 

Looking at the implementation of `app_layer`, the `workdir` and `directory` attrs are set together (with default value to `/app`). 
https://github.com/bazelbuild/rules_docker/blob/74441f0d7000dde42ce02c30ce2d1bf6c0c1eebc/lang/image.bzl#L254

Could you also override `workdir` attr as well in your PR?

**Comment by erain** [comment]
Hi @justinwp : could you help address the comment so I can merge your PR? Thanks!

**Comment by nlopezgi** [comment]
Hi @justinwp, is this PR still needed? Can you please address the feedback when you have the chance? Thanks for your patience and contribution!

**Comment by nlopezgi** [comment]
Please re-open when you are ready to pick this up. Thanks again for your contributions!

**Pull request closed without merging**
