### PR TITLE
Fix error message in pusher

### PR DESCRIPTION
**Pull request by xiaohegong**
Fixed a typo in an error message used by `log.Fatalln` in `pusher.go`.

### CODE REVIEW

**Comment by xiaohegong** [comment]
Thank you @factuno-db for pointing it out :)

**Comment by xingao267** [comment]
Rebase after https://github.com/bazelbuild/rules_docker/pull/971 is merged to fix the test.

**Comment by cjwagner** [comment]
/hold
https://github.com/bazelbuild/rules_docker/issues/862

**Pull request merged**
