### PR TITLE
using better approach to file output

### PR DESCRIPTION
**Pull request by tejal29**
Cherrypicking @schoren's commit onto my branch.

### CODE REVIEW

**Comment by tejal29** [comment]
@googlebot i confirm

**Comment by tejal29** [comment]
@dlorenc we have a CLA state no and its up to maintainers to merge this in.
Are you ok doing this?
@schoren i am cherrypicking your one commit on this PR. Cherry picking will ensure your name is in the authors.
If this approach does not work, you will have to create a new PR with just your change.

**Comment by schoren** [comment]
@tejal29 thanks! I'll watch this PR and make a new one if it fails.

**Comment by dlorenc** [comment]
@bazel-io test this please

**Comment by tejal29** [comment]
@dlorenc this is ready to merge in.

**Comment by tejal29** [comment]
@mattmoor we have a PR with multiple commits
Can you help us out here.

**Comment by mattmoor** [comment]
I only see one commit, but you can "Squash and merge" through the Github UI.  I'll make sure Dan has super powers.

**Pull request merged**
