### PR TITLE
Add ppc64le support to load puller and loader binaries

### PR DESCRIPTION
**Pull request by rmohr**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

A follow up of  #1791, addresses #1790

## What is the new behavior?

Add attributes for ppc64le for the pull and load rules.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

How do the shasums get propagated on release? The repository part is basically a mock.

### CODE REVIEW

**Comment by pcj** [comment]
@rmohr Thanks for your contribution.  Once we get our CI fixed up we'll look to get this merged.  

Note this PR will need to be modified if https://github.com/bazelbuild/rules_docker/pull/1795 lands.

**Comment by zoidbergwill** [comment]
I can totally add `ppc64le` to the CI in my MR, or we can merge this first.

**Comment by rmohr** [comment]
> I can totally add `ppc64le` to the CI in my MR, or we can merge this first.

I am out for a few days, whatever works best for you :)

**Comment by rmohr** [comment]
> I can totally add `ppc64le` to the CI in my MR, or we can merge this first.

I would be back. Let me know if you want me to do anything on the PR.

**Pull request closed without merging**
