### PR TITLE
Upgrade to v0.0.7 of google/containerregistry

### PR DESCRIPTION
**Pull request by mattmoor**
Switch to using the new relaxed naming to fix the linked issue.

Fixes: https://github.com/bazelbuild/rules_docker/issues/28

### CODE REVIEW

**Comment by mattmoor** [comment]
I'm just opening the PR for now to test things, I'd like to experiment with adding some better test coverage for this case.

**Comment by mattmoor** [comment]
@damienmg Do you have any good examples of how I might ~embed a test like I have in `testing/top-level/` within the repo?

**Comment by damienmg** [comment]
I don't really understand what you are asking for, can you give an example of what you would like to do?

**Comment by mattmoor** [comment]
tl;dr https://github.com/bazelbuild/bazel/issues/2751

I am going to move these files into a shell script that will run end to end tests and invoke it from Travis.

**Pull request merged**
