### PR TITLE
Add arm64 support to load puller and loader binaries

### PR DESCRIPTION
**Pull request by tcnghia**
Similar to what https://github.com/bazelbuild/rules_docker/pull/1661 does for s390x.

### CODE REVIEW

**Comment by tcnghia** [comment]
@cgdolan @smukherj1 can you please help review? thank you.

**Comment by cgdolan** [comment]
Hi Nghia - thanks so much for this change. I'm super excited for this to land, unfortunately I'm not an OWNER so I am unable to review this change.

**Review by DaveGay — APPROVED** [review]

**Comment by DaveGay** [comment]
Please fix the buildkite formatting issue.

(Download buildifier 0.22.0 and run: buildifier container/load.bzl repositories/repositories.bzl )

**Comment by tcnghia** [comment]
> Please fix the buildkite formatting issue.
> 
> (Download buildifier 0.22.0 and run: buildifier container/load.bzl repositories/repositories.bzl )

@DaveGay Done. Thanks!

**Comment by tcnghia** [comment]
@DaveGay it seems the CI run is stuck (waiting for status for more than a day now). I wonder if this is just a workflow issue or does it indicate some problem with the change?

**Comment by DaveGay** [comment]
@tcnghia Looks like the check passed but the notification got lost.  Merged, and thanks!

**Pull request merged**
