### PR TITLE
Add support for print_progress to container_pull

### PR DESCRIPTION
**Pull request by scele**
Add minimal prints to indicate puller progress if container_pull
has print_progress=True attribute.  The intention is that the pull
operation would provide some feedback to the user, instead of bazel
getting seemingly stuck for 10 minutes when pulling an image that is
many gigabytes in size.

Pending pull request to upstream puller.par is here:
https://github.com/google/containerregistry/pull/66

### CODE REVIEW

**Comment by scele** [comment]
@nlopezgi any thoughts on this? We've had problems with developers reporting "bazel is stuck", and turns out it was just pulling a big image for 10 minutes. There are other ways to expose this, for example adding `quiet=True|False` and `puller_args=[string]` flags. Or ideally workspace rules could support `mnemonic`, like actions, but that would need to go into bazel core..

If you agree something like this is a good idea, perhaps you could vouch for the related puller.par change that hasn't gotten much attention here: https://github.com/google/containerregistry/pull/66

**Comment by ittaiz** [comment]
+100 this is a big problem for us as well

**Comment by ittaiz** [comment]
Is it worth while adding the attribute and quiet=false for now? It will bring better info for failure cases I think

**Comment by nlopezgi** [comment]
is this PR still relevant now that we're moving to go containerregistry? let me know if so, otherwise i'll close.

**Comment by scele** [comment]
Not in its current form at least. Closing.

**Pull request closed without merging**
