### PR TITLE
Add a build target for the new "layer" rule.

### PR DESCRIPTION
**Pull request by pawelz**

### CODE REVIEW

**Comment by pawelz** [comment]
Hi, is something blocking this pull request? Can I ask for it to be merged? Thanks!

**Comment by mattmoor** [comment]
Probably me paying attention to the CI results and hitting merge :(

**Comment by pawelz** [comment]
No worries, just asking. Thanks!

**Comment by pawelz** [comment]
So it's green again, and re-based to head. Merge? :-)

**Pull request merged**
