### PR TITLE
Add a `null_entrypoint` attribute to app_layer

### PR DESCRIPTION
**Pull request by siddharthab**
This allows people to not use the default entrypoint which is geared
towards runnig the container as executable with one or more arguments.

With zero arguments also, it is a problem when the base image already
specifies a Cmd in its config. Because that becomes the argument to
the executable and there is no way to override it currently.

See https://github.com/google/containerregistry/pull/86

Resolves https://github.com/bazelbuild/rules_docker/issues/379

### CODE REVIEW

**Comment by erain** [comment]
Hi @siddharthab : IIUC `app_layer` is not meant to be directly, rather it is used in those `lang_image` rules which needs to be compatible with the corresponding bazel `lang_binary` rules. 

Also, if you are reusing `app_layer` rules, could you give me a concrete case where you need an extra attr `null_entrypoint` rather than set `entrypoint` to null directly?

**Comment by siddharthab** [comment]
I think all of this is discussed in https://github.com/bazelbuild/rules_docker/issues/379

The lang_image rules allows you to specify a base image. Some of these base images already have a Cmd attribute defined in their layers. This Cmd attribute then becomes an argument to the executable which is undesirable behavior (suggested https://github.com/google/containerregistry/pull/86 for this). See for example, the workaround I had to do for R images -- https://github.com/grailbio/rules_r/blob/928e1300dd9b59794bdb8a8234bc9ed47ff8f90e/R/container/binary.bzl#L104

The other use case is when you want to use the lang_image in an external system where they will provide their own Cmd, where they assume that the entry point is null. Like se do so in https://github.com/grailbio/reflow. Ideally, the entry point should be reset by such systems when executing the image, but sometimes end users can not control these things.

Overall, I think it is a good idea to give some control to the end users.

**Comment by siddharthab** [comment]
One more thing if it's not clear. The lang_image rules are macros that pass on their attributes to app_layer rules. So end users will be able to specify a null entrypoint per image target.

**Comment by siddharthab** [comment]
Just realised https://github.com/bazelbuild/rules_docker/issues/379 talks about a related problem but not this. Sorry about that. My comment there is what this PR tries to resolve.

**Comment by siddharthab** [comment]
On thinking more about this, I realize now that a proper solution will be to have a mechanism [here](https://github.com/siddharthab/containerregistry/blob/master/transform/v2_2/metadata_.py) to clear the default values without setting a new value. Right now, there is no such mechanism. If we can think of a way to clear attributes from base images without specifying new ones, then this PR is not needed.

**Comment by erain** [comment]
Hi @siddharthab sorry to late for this issue. 

My understand in #379 is to solve the problem in `container_image` layer as @mattmoor indicated, to have `entrypoint=[]` behave in a way that it will override the entrypoint of the base container (or any layers in between. Therefore, we can have the same behavior as you implemented without adding a new attr. 

As for `cmd` attr, I guess we can implement the same as `entrypoint`, so users have the flexibility to set whatever combination they want. 

Would you like to help implement the feature listed?

**Comment by siddharthab** [comment]
That is correct. Except I can not think of a way to do this in skylark/python without breaking existing behaviour.

**Comment by xingao267** [comment]
Created https://github.com/bazelbuild/rules_docker/pull/471 to properly set null entrypoint and cmd in container_image rule.

**Comment by siddharthab** [comment]
Closing this in favor of the other PR.

**Pull request closed without merging**
