### PR TITLE
Add repository_file attribute to the container_pull rule

### PR DESCRIPTION
**Pull request by nlewo**
This attribute allows to set the repository value from a file as it is
already possible for the tag thanks to the tag_file attribute.

### CODE REVIEW

**Comment by nlewo** [comment]
Note we always need to provide the `repository` attribute because it is mandatory. Since for most use cases the `repository` attribute should be sufficient, i think it would be better to preserve this behavior.
WDYT?

**Comment by smukherj1** [comment]
Seems reasonable to have `repository_file` given `tag_file` already exists. Feel free to update the [pusher](https://github.com/bazelbuild/rules_docker/blob/master/container/go/cmd/pusher/pusher.go) binary to implement this.

**Comment by nlewo** [comment]
@smukherj1 What exactly should i implement in the pushed binary? 
The `repository_file` (and `tag_file`) value is substituted by bash (in the generated bash script): the pusher takes as argument a string such as `--dst=repository:$(cat ${RUNFILES}/tag)`, where `$(cat ${RUNFILES}/tag)` is evaluated by bash.

**Comment by smukherj1** [comment]
Apologies, I missed the `cat`.

**Review by smukherj1 — APPROVED** [review]

**Comment by nlewo** [comment]
Thanks ;)

**Pull request merged**
