### PR TITLE
Allow passwd entry with non-existing home path

### PR DESCRIPTION
**Pull request by chanseokoh**
This will be useful to create an entry like `nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin`.

I'm new to Starlark, so I need some help actually.

### CODE REVIEW

**Comment by xingao267** [comment]
Hi @chanseokoh thanks for the PR, could you add passwd_entry, passwd_file, passwd_tar targets for this use case and tests in testdata/BUILD? Like these ones https://github.com/bazelbuild/rules_docker/blob/master/testdata/BUILD#L517

**Comment by chanseokoh** [comment]
Thanks @xingao267, will do (some time later).

**Comment by chanseokoh** [comment]
Added tests. Hopefully the tests pass on Travis. I couldn't run tests locally. Don't know what's wrong.

```
$ bazel test //container:image_test
INFO: Invocation ID: caf22c72-2cba-457c-baa8-f45f82348e1d
ERROR: .../rules_docker/lang/image.bzl:320:44: name 'PyInfo' is not defined (did you mean 'ApkInfo'?)
ERROR: error loading package '': in .../rules_docker/python/image.bzl: Extension 'lang/image.bzl' has errors
ERROR: error loading package '': in .../rules_docker/python/image.bzl: Extension 'lang/image.bzl' has errors
INFO: Elapsed time: 0.122s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by chanseokoh** [comment]
Never mind. Using the latest Bazel works. There seem test failures, so I'll fix them.

**Comment by chanseokoh** [comment]
Tests passing. I believe the `self.assertTopLayerContains(img, ['.', './etc', './etc/password', './root', './myhomedir'])` confirms that `/nonexistent` doesn't exist in the tar??

**Comment by chanseokoh** [comment]
Indeed, I verified an actual image created with `create_home = False`, and it doesn't create the directory.

**Pull request merged**
