### PR TITLE
Fixed incorrect documentation

### PR DESCRIPTION
**Pull request by excavador**
Noted in README.md "base" syntax is not workable

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by mattmoor** [comment]
@excavador That syntax is correct and is significantly more efficient (doesn't require linking the tarball).  Can you elaborate a bit more on what you are doing or link to an example?

Are you perhaps using the version of `docker_build` bundled with Bazel (deprecated) instead of this version (new / improved)?

**Comment by excavador** [comment]
@mattmoor please take a look to example
https://github.com/excavador/docker_bazel_naming_problem/tree/reference_to_image_problem

```➜ bazel build //docker/postgresql/...
..............
WARNING: /private/var/tmp/_bazel_oleg/bb8329684d4f92473190c24d9fe97e93/external/bazel_tools/tools/build_defs/docker/docker.bzl:19:1: The docker_{build,bundle} rules bundled with Bazel are deprecated in favor of:
https://github.com/bazelbuild/rules_docker. Please change BUILD loads to reference: @io_bazel_rules_docker//docker:docker.bzl and add the following to your WORKSPACE:
git_repository(
    name = "io_bazel_rules_docker",
    remote = "https://github.com/bazelbuild/rules_docker.git",
    commit = "...",
)
load("@io_bazel_rules_docker//docker:docker.bzl", "docker_repositories")
docker_repositories().
ERROR: /Users/oleg/dev/docker_bazel_naming_problem/docker/postgresql/BUILD:6:1: no such target '@official_postgresql//image:image': target 'image' not declared in package 'image' defined by /private/var/tmp/_bazel_oleg/bb8329684d4f92473190c24d9fe97e93/external/official_postgresql/image/BUILD and referenced by '//docker/postgresql:latest'.
ERROR: Analysis of target '//docker/postgresql:latest' failed; build aborted.
INFO: Elapsed time: 21.241s```

**Comment by excavador** [comment]
```➜ bazel version
Build label: 0.5.3-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jul 27 19:30:37 2017 (1501183837)
Build timestamp: 1501183837
Build timestamp as int: 1501183837```

**Comment by mattmoor** [comment]
@excavador Yeah, [this is using](https://github.com/excavador/docker_bazel_naming_problem/blob/reference_to_image_problem/docker/postgresql/BUILD#L2) the version of `docker_build` bundled with Bazel (thus the warning).

**Comment by excavador** [comment]
@mattmoor switched, still have the problem
See branch updates:
https://github.com/excavador/docker_bazel_naming_problem/tree/reference_to_image_problem

**Comment by mattmoor** [comment]
Ah, I see what's going on.  The `v0.0.2` release (currently latest and what's documented) doesn't have some of the performance improvements that enable you to drop the `:image.tar`.  This should work (it does for me) if you change things to `commit = "<hash @ HEAD>"` in your `WORKSPACE`.  

I'll cut a new release and update the docs to use the new release tag momentarily, sorry for the trouble.

**Comment by excavador** [comment]
@mattmoor I confirm. With commit = "hash of HEAD" everything works fine.
Please update related documentation and after that github issue can be closed.
Thank you!

**Comment by mattmoor** [comment]
@excavador I just cut the release and updated the README at HEAD, so hopefully other folks won't hit this.  Sorry for the trouble, and definitely LMK if you hit any other problems.

Thanks for reaching out.

**Pull request closed without merging**
