### PR TITLE
Remove usages of deprecated Bazel features

### PR DESCRIPTION
**Pull request by jjudd**
This makes rules_docker compatible with `--all_incompatible_changes`, best I can tell.

### CODE REVIEW

**Comment by jjudd** [comment]
I was updating our internal version of Bazel to 0.16 and these errors showed up with `--all_incompatible_changes` enabled, so I fixed them.

**Comment by nlopezgi** [comment]
Would you mind running buildifier on the files you changed (https://github.com/bazelbuild/buildtools/tree/master/buildifier) to format properly. Thanks!

**Comment by jjudd** [comment]
Sure thing. Will do.

**Comment by nlopezgi** [comment]
Got this in earlier as we're expecting to merge a large PR in a bit and dont want to create any conflicts

**Pull request closed without merging**
