### PR TITLE
Fixed passing data to app_layer in nodejs_image

### PR DESCRIPTION
**Pull request by gcangussu**
We were getting `data` from `kwargs`, but it will always be `None` since we declare an explicit `data` in the function parameters. This only passes the `data` function parameter to the `app_layer` data.

This fix is required for using arguments on the `nodejs_image`, e.g.:

```starlark
nodejs_image(
    name = "my_image",
    binary = ":my_bin",
    args = ["$(rootpath config.json)"],
    data = ["config.json"],
)
```

### CODE REVIEW

**Comment by gcangussu** [comment]
@googlebot I signed it!

**Comment by smukherj1** [comment]
Please update the base branch so that I can kick off the tests and merge this PR

**Comment by gcangussu** [comment]
@smukherj1 I've merged my branch with master, is that what you meant by updating the base branch?

**Comment by smukherj1** [comment]
> @smukherj1 I've merged my branch with master, is that what you meant by updating the base branch?

Yep

**Pull request merged**
