### PR TITLE
Issue 1022 update readme with details on known issue

### PR DESCRIPTION
**Pull request by raulAtNines**
- Modify Readme to add information about issue #1022 
  - Add Known Issues sub section to `Setup` with previous information
  - Add note and details about #1022

### CODE REVIEW

**Comment by nlopezgi** [comment]
Thanks for sending this PR. Can you please do the CLA as indicated [above](https://github.com/bazelbuild/rules_docker/pull/1042#issuecomment-516963982) and then we can merge?
Thanks again

**Comment by raulAtNines** [comment]
@nlopezgi Our corporate CLA has been signed, I should get it cleared soon. Thank you.

**Comment by raulAtNines** [comment]
@googlebot I signed it!

**Comment by raulAtNines** [comment]
@googlebot I signed it!

**Comment by raulAtNines** [comment]
@nlopezgi The CLA was approved. I think I messed it up by updating the PR to latest master. Can you help with that? It's otherwise ready.

**Comment by nlopezgi** [comment]
thanks, looks like the cla bot is somehow stuck. Given this PR has a trace of you accepting the CLA, I can manually squash and merge overriding the check.

**Comment by raulAtNines** [comment]
Great! Thanks.

**Pull request merged**
