### PR TITLE
Support for docker run args for docker image targets

### PR DESCRIPTION
**Pull request by psigen**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

The `bazel run` command applied to docker images currently does not have functionality to pass any arguments to the underlying docker run command.  This means that it is impossible to use docker image targets to perform things like CLI operations on files, or set their network settings.

Issue Number: N/A

## What is the new behavior?

This PR changes `bazel run`'s behavior on image targets to mirror `docker run`'s behavior.  Docker images can now be run with arbitrary docker flags like:

```
bazel run //:my_image -- -v /path/to/file:/path/inside/container -- arg0 arg1 arg2
```

which mirrors a call to

```
docker run -v /path/to/file:/path/inside/container bazel/my_image -- arg0 arg1 arg2
```

Since `--norun` is not a valid docker run flag, we can strip and parse it with no changes, preserving existing functionality.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Can someone please help me with defining appropriate testing and documentation for this change? :pray:

### CODE REVIEW

**Review by gravypod — COMMENTED** [review]
I don't see any initial reason to not merge this. @alexeagle any thoughts? It looks like it should be backwards compatible.

**Comment by psigen** [comment]
@gravypod Since previously all the args were just being ignored and we preserved --norun, I think this should be backwards-compatible :+1:

**Comment by psigen** [comment]
Where could I add a unit test for the behavior?  I think I got the docs change.

**Comment by UebelAndre** [comment]
@psigen @gravypod friendly ping 😅 any way to move this change forward? It'd be a very convenient feature!

**Comment by psigen** [comment]
I'd love to move this change forward! Please just let me know what I need to do next to get it approved :smile:

**Comment by UebelAndre** [comment]
For starters. It seems there's a build failure in CI. Fixing that may move this forward

**Comment by psigen** [comment]
The build failure has nothing to do with this PR though (I changed the
readme in that commit and the failure seems to be an image fetch failure).

Is there a way to re-kick the build? I guess I can just fiddle with
whitespace to make it rebuild.

**Comment by psigen** [comment]
I have successfully reworded the `README.md` hard enough to fix the pkg install build reproducibility tests :shrug:

**Review by gravypod — COMMENTED** [review]
Thanks for updating the docs. Looks good to me now. Going to check in with @alexeagle but I think this should be backwards compatible.

**Comment by gravypod** [comment]
Just remembered, we've previously discussed this. I think we're good to go here.

**Review by gravypod — APPROVED** [review]

**Comment by psigen** [comment]
Thanks @gravypod!

**Comment by robmartorano** [comment]
I think there may have been a mistake in the merge earlier in this PR, line `"%{run_tag}": run_tag,` was lost in `layer_tools.bzl`, which results in `bazel run` not working against head. Adding that line back results in things working. Great feature addition overall!

**Pull request merged**
