### PR TITLE
Update distroless images with running update_deps.sh

### PR DESCRIPTION
**Pull request by dragon3**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe: Update distroless images

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

It's been 10 months since the images were updated last time. 
As described in [README.md](https://github.com/bazelbuild/rules_docker#updating-the-distroless-base-images), it's better to update the distroless base images over time to pick up bug fixes and security patches :smile:

<details><summary>update_deps.sh command log</summary>

```sh
➜  rules_docker git:(update-distroless-deps) ✗ ./update_deps.sh
2022/09/30 10:05:55 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
2022/09/30 10:05:55 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Analyzed target //container/go/cmd/update_deps:update_deps (4 packages loaded, 80 targets configured).
INFO: Found 1 target...
Target //container/go/cmd/update_deps:update_deps up-to-date:
  bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps
INFO: Elapsed time: 2.378s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps '--repository=gcr.io/distroless/base' '--output=/Users/dragon3/src/gitINFO: Build completed successfully, 1 total action
2022/09/30 10:06:02 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
2022/09/30 10:06:02 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Analyzed target //container/go/cmd/update_deps:update_deps (4 packages loaded, 80 targets configured).
INFO: Found 1 target...
Target //container/go/cmd/update_deps:update_deps up-to-date:
  bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps
INFO: Elapsed time: 1.919s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps '--repository=gcr.io/distroless/static' '--output=/Users/dragon3/src/gINFO: Build completed successfully, 1 total action
2022/09/30 10:06:08 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
2022/09/30 10:06:08 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Analyzed target //container/go/cmd/update_deps:update_deps (4 packages loaded, 80 targets configured).
INFO: Found 1 target...
Target //container/go/cmd/update_deps:update_deps up-to-date:
  bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps
INFO: Elapsed time: 1.218s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps '--repository=gcr.io/distroless/cc' '--output=/Users/dragon3/src/githuINFO: Build completed successfully, 1 total action
2022/09/30 10:06:14 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
2022/09/30 10:06:14 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Analyzed target //container/go/cmd/update_deps:update_deps (4 packages loaded, 80 targets configured).
INFO: Found 1 target...
Target //container/go/cmd/update_deps:update_deps up-to-date:
  bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps
INFO: Elapsed time: 1.320s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps '--repository=gcr.io/distroless/python2.7' '--output=/Users/dragon3/srINFO: Build completed successfully, 1 total action
2022/09/30 10:06:19 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
2022/09/30 10:06:19 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Analyzed target //container/go/cmd/update_deps:update_deps (4 packages loaded, 80 targets configured).
INFO: Found 1 target...
Target //container/go/cmd/update_deps:update_deps up-to-date:
  bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps
INFO: Elapsed time: 1.785s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps '--repository=gcr.io/distroless/python3' '--output=/Users/dragon3/src/INFO: Build completed successfully, 1 total action
2022/09/30 10:06:25 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
2022/09/30 10:06:25 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Analyzed target //container/go/cmd/update_deps:update_deps (4 packages loaded, 80 targets configured).
INFO: Found 1 target...
Target //container/go/cmd/update_deps:update_deps up-to-date:
  bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps
INFO: Elapsed time: 1.378s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps '--repository=gcr.io/distroless/java' '--output=/Users/dragon3/src/gitINFO: Build completed successfully, 1 total action
2022/09/30 10:06:29 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
2022/09/30 10:06:29 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Analyzed target //container/go/cmd/update_deps:update_deps (4 packages loaded, 80 targets configured).
INFO: Found 1 target...
Target //container/go/cmd/update_deps:update_deps up-to-date:
  bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps
INFO: Found 1 target...
Target //container/go/cmd/update_deps:update_deps up-to-date:
  bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps
INFO: Elapsed time: 1.329s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps '--repository=gcr.io/distroless/java/jetty' '--output=/Users/dragon3/sINFO: Build completed successfully, 1 total action
2022/09/30 10:06:34 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
2022/09/30 10:06:34 WARN: Fallback to x86_64 because arm64 is not supported on Apple Silicon until 4.1.0
INFO: Analyzed target //container/go/cmd/update_deps:update_deps (4 packages loaded, 80 targets configured).
INFO: Found 1 target...
Target //container/go/cmd/update_deps:update_deps up-to-date:
  bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps
INFO: Elapsed time: 1.304s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/container/go/cmd/update_deps/update_deps_/update_deps '--repository=gcr.io/google-appengine/debian9' '--output=/Users/dragonINFO: Build completed successfully, 1 total action
```

</details>

### CODE REVIEW

**Comment by ensonic** [comment]
Container scans already list ~20 CVEs, would be really nice to update the base images.

**Comment by linzhp** [comment]
Can you merge from master to see if the CI passes?

**Comment by dragon3** [comment]
Thank you for the comments 😄 
I've merged from master and run `update_deps.sh` again. Now all CI checks have passed 👍

**Review by linzhp — APPROVED** [review]

**Comment by dragon3** [comment]
Thank you for reviewing and merging!
I'm looking forward to the new version with this change 😄

**Comment by dragon3** [comment]
I thought it's better to run `update_deps.sh` and create pull request periodically using GitHub Actions or something else.
I can set up it if necessary 😄

**Comment by ensonic** [comment]
I think automating this would be great. Imho it makes most sense to do this when nearing a release. Now it has been updates, but it won't help as there has not been a release for half a year.

**Pull request merged**
