### PR TITLE
Expose architecture in container_image

### PR DESCRIPTION
**Pull request by murilofv**
container_image builds all images labeled as amd64 despite the
possibility of it being intended for another architecture, without a way
to overwrite this value. Aside from being confusing to a user, this could
also be an issue when using said images as part of a manifest list, given
the wrong label won't pull the proper image to the system.

This patch exposes an architecture attribute that can be used by an user
in order to properly label the container image. The default is still amd64
in case it is not set.

It also adds a sh_test called architecture_test to verify that when a
labeled is set it was actually be properly modified in the config of the
target image.

Signed-off-by: Murilo Fossa Vicentini <muvic@linux.ibm.com>

Fixes https://github.com/bazelbuild/rules_docker/issues/1421

### CODE REVIEW

**Comment by murilofv** [comment]
@smukherj1 is this what you had in mind regarding for your comment in https://github.com/bazelbuild/rules_docker/issues/1421#issuecomment-587500437 ?

**Comment by murilofv** [comment]
@googlebot I signed it!

**Comment by murilofv** [comment]
> Thanks! The PR looks good! Could you please add a test? I suggest adding a `container_image` target [here](https://github.com/bazelbuild/rules_docker/blob/master/tests/container/BUILD) and then maybe write a `sh_test` that depends on the `<target>.json` and validates that the architecture string is present in the config.

Sure, I can do that, do you want me to run it as as part of any automated test currently in place like `.bazelci/presubmit.yml` or `testing/e2e.sh` or you want me to just add it so folks can run it manually if needed?

**Comment by smukherj1** [comment]
> > Thanks! The PR looks good! Could you please add a test? I suggest adding a `container_image` target [here](https://github.com/bazelbuild/rules_docker/blob/master/tests/container/BUILD) and then maybe write a `sh_test` that depends on the `<target>.json` and validates that the architecture string is present in the config.
> 
> Sure, I can do that, do you want me to run it as as part of any automated test currently in place like `.bazelci/presubmit.yml` or `testing/e2e.sh` or you want me to just add it so folks can run it manually if needed?

Would prefer it runs automatically in the Bazel CI presubmit which it should (if added as an sh_test target) unless explicitly excluded in the `.bazelci/presubmit.yaml` file.

**Comment by murilofv** [comment]
> Would prefer it runs automatically in the Bazel CI presubmit which it should (if added as an sh_test target) unless explicitly excluded in the `.bazelci/presubmit.yaml` file.

I might be missing something, was it expected to run automatically indeed? I am looking at the build results in https://buildkite.com/bazel/rules-docker-docker/builds/3872 and I don't see the test listed there. I assume it doesn't actually run automatically and I need to explicitly make it a part of test_targets in `.bazelci/presubmit.yaml`, is this the case?

**Comment by smukherj1** [comment]
> > Would prefer it runs automatically in the Bazel CI presubmit which it should (if added as an sh_test target) unless explicitly excluded in the `.bazelci/presubmit.yaml` file.
> 
> I might be missing something, was it expected to run automatically indeed? I am looking at the build results in https://buildkite.com/bazel/rules-docker-docker/builds/3872 and I don't see the test listed there. I assume it doesn't actually run automatically and I need to explicitly make it a part of test_targets in `.bazelci/presubmit.yaml`, is this the case?

Apologies. I was assuming we used `bazel test ...` to run the test and only listed `-<taget>` for tests we wanted to exclude. I see this was changed by this [commit](https://github.com/bazelbuild/rules_docker/commit/0237f78e90155e5d0095ed1ec6780cea1b618964). So yes, please go ahead and add your new test to the presubmit.yaml for all the test environments.

**Comment by murilofv** [comment]
> > > Would prefer it runs automatically in the Bazel CI presubmit which it should (if added as an sh_test target) unless explicitly excluded in the `.bazelci/presubmit.yaml` file.
> > 
> > 
> > I might be missing something, was it expected to run automatically indeed? I am looking at the build results in https://buildkite.com/bazel/rules-docker-docker/builds/3872 and I don't see the test listed there. I assume it doesn't actually run automatically and I need to explicitly make it a part of test_targets in `.bazelci/presubmit.yaml`, is this the case?
> 
> Apologies. I was assuming we used `bazel test ...` to run the test and only listed `-<taget>` for tests we wanted to exclude. I see this was changed by this [commit](https://github.com/bazelbuild/rules_docker/commit/0237f78e90155e5d0095ed1ec6780cea1b618964). So yes, please go ahead and add your new test to the presubmit.yaml for all the test environments.

No problem, I added there an it shows up now, thank you. Let me know if you have any additional feedback / concerns regarding the patch.

**Comment by murilofv** [comment]
Just out of curiosity, now that I noticed, did something happen that the commit message body was not added during the merge? This doesn't look like something expected, but I unfortunately deleted the branch / fork after the merge happened and looks like the references were lost, so haven't been able to look into what could possibly have happened.

**Pull request merged**
