### PR TITLE
Add support for pulling docker images on Apple Silicon

### PR DESCRIPTION
**Pull request by connyay**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by connyay** [comment]
Supersedes https://github.com/bazelbuild/rules_docker/pull/2033

now that https://github.com/bazelbuild/rules_docker/pull/2169 landed this should be closer to landing... 

Just need a maintainer to run https://github.com/bazelbuild/rules_docker/actions/workflows/add_binaries_to_release.yml to get a published binary to point to 👀 

@linzhp - do you have perms to kick that workflow? 👀

**Comment by connyay** [comment]
actually... maybe #2033 was wrong... I prob should have added to https://github.com/bazelbuild/rules_docker/blob/def5c9644be8eddb2637c8619198152d3c2f0c33/container/go/cloudbuild.yaml#L129-L159 ?

🤔

**Comment by linzhp** [comment]
I don't see a "Run Workflow" button. @gravypod can you run it?

**Comment by connyay** [comment]
I think I goofed. mixing CI envs https://github.com/bazelbuild/rules_docker/pull/2192

**Pull request closed without merging**
