### PR TITLE
Update container-structure-test binaries to v0.11.0

### PR DESCRIPTION
**Pull request by dbrian**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Version 1.9.1 of the container-structure-test-darwin-amd64 binary is not compatible with MacOS Monterey. 

```
❯ ./container-structure-test-darwin-amd64
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x15e1aff, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0x7ff7bfeff6f0 sp=0x7ff7bfeff6d0 pc=0x102a1b5
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0x83 fp=0x7ff7bfeff720 sp=0x7ff7bfeff6f0 pc=0x1027a53
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:492 +0xa4 fp=0x7ff7bfeff760 sp=0x7ff7bfeff720 pc=0x102cb94
runtime.rt0_go(0x7ff7bfeff798, 0x1, 0x7ff7bfeff798, 0x0, 0x1000000, 0x1, 0x7ff7bfeff978, 0x0, 0x7ff7bfeff9a0, 0x7ff7bfeff9dc, ...)
	/usr/local/go/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7ff7bfeff768 sp=0x7ff7bfeff760 pc=0x105452b
```

Issue Number: #2012

## What is the new behavior?

Version 1.11.0 works as expected.

```
❯ ./container-structure-test-darwin-amd64
container-structure-test provides a powerful framework to validate
the structure of a container image.
These tests can be used to check the output of commands in an image,
as well as verify metadata and contents of the filesystem.

Usage:
  container-structure-test [command]
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by marcguilera** [comment]
This solves the issue for me

**Comment by jotadrilo** [comment]
Hello there! This patch works like a charm for me too. Do we guys plan to include this in the next release?

**Comment by jcourteau** [comment]
This may be sufficient to re-enable the tests that were disabled in #1952

**Review by alexeagle — APPROVED** [review]
thanks!

**Pull request merged**
