### PR TITLE
Plumb constraints thru container_test

### PR DESCRIPTION
**Pull request by mattmoor**
Upgrade to 1.9.1 and include arm64 support.

cc @nkubala @nlopezgi

### CODE REVIEW

**Comment by mattmoor** [comment]
In the PR linked above, I'm using rules_docker to build and run arm64 distroless containers.

**Review by smukherj1 — APPROVED** [review]

**Comment by mattmoor** [comment]
@smukherj1 I think I need some more magic commands 😅

**Comment by smukherj1** [comment]
@mattmoor you're first in line after https://github.com/bazelbuild/rules_docker/pull/1640 ;)

The GCB tests take a long time to run and rules_docker merging restrictions mean the tests need to pass at HEAD. So effectively, I manually serialize running GCB tests & merging PRs

ofc this is horrible and if I could spend more time on this I would work on improving this but ... :(

**Comment by mattmoor** [comment]
> The GCB tests

What are these actually testing?

**Comment by smukherj1** [comment]
e2e tests mostly. Look for YAML files in https://github.com/bazelbuild/rules_docker/tree/master/testing

I believe various configurations of the puller & pusher

**Comment by mattmoor** [comment]
💥 thanks!

**Pull request merged**
