### PR TITLE
Update to container-structure-test 1.8.0

### PR DESCRIPTION
**Pull request by briandealwis**
container-structure-test 1.7.0 adds the ability to test image metadata with regexs.

_Updated to container-structure-test v1.8.0, which pulls in the 0-byte layer.tar fix from 
google/go-containerregistry_

### CODE REVIEW

**Comment by nlopezgi** [comment]
looks like the windows tests are failing, the error message is not too descriptive, but does seem to point to 1.7.0 being problematic

**Comment by briandealwis** [comment]
Too bad the tests are run with `--quiet`!  I can reproduce locally:
```
$ bazel-out/darwin-fastbuild/bin/structure_test_at_workspace_root.runfiles/structure_test_darwin/file/downloaded version
v1.7.0
$ bazel-out/darwin-fastbuild/bin/structure_test_at_workspace_root.runfiles/structure_test_darwin/file/downloaded test --driver tar --image bazel-out/darwin-fastbuild/bin/tests/docker/basic_windows_image.tar --config tests/docker/configs/windows_image.yaml

===========================================
====== Test file: windows_image.yaml ======
===========================================
=== RUN: Files
--- FAIL
Error: error creating driver: processing tar image reference: retrieving tar from path: EOF

=== RUN: Hives
--- FAIL
Error: error creating driver: processing tar image reference: retrieving tar from path: EOF

=== RUN: Metadata Test
--- FAIL
Error: error creating driver: processing tar image reference: retrieving tar from path: EOF


===========================================
================= RESULTS =================
===========================================
Passes:      0
Failures:    3
Total tests: 3

FAIL
FATA[0000] FAIL                                         
```

**Comment by briandealwis** [comment]
I'm assuming the local failure is the same as what's happening on the build machine.  It's odd that the other builds all pass though.

**Comment by briandealwis** [comment]
I opened GoogleContainerTools/container-structure-test#197 and did some initial digging.

It turns out that the generated Windows images have 0-byte layer.tar files which seems … unusual?
```
$ tar bazel-out/darwin-fastbuild/bin/tests/docker/basic_windows_image.tar 
-rw-r--r--  0 0      0         907 31 Dec  1969 378fb1f1c5d59102b2b942e7c5cd76ce913cb5a4b74e97f87041dc61ab14b21e.json
-rw-r--r--  0 0      0           3 31 Dec  1969 0239ecd27132f0d70c7946a5365ef1f0a3edc7ecf6bdeeb61b4215598beb9828/VERSION
-rw-r--r--  0 0      0       10240 31 Dec  1969 0239ecd27132f0d70c7946a5365ef1f0a3edc7ecf6bdeeb61b4215598beb9828/layer.tar
-rw-r--r--  0 0      0         461 31 Dec  1969 0239ecd27132f0d70c7946a5365ef1f0a3edc7ecf6bdeeb61b4215598beb9828/json
-rw-r--r--  0 0      0           3 31 Dec  1969 54625cd3a0909e177f99d40c983676e65cd2ba5e3231670bd3b3a060463e384c/VERSION
-rw-r--r--  0 0      0           0 31 Dec  1969 54625cd3a0909e177f99d40c983676e65cd2ba5e3231670bd3b3a060463e384c/layer.tar
-rw-r--r--  0 0      0         250 31 Dec  1969 54625cd3a0909e177f99d40c983676e65cd2ba5e3231670bd3b3a060463e384c/json
-rw-r--r--  0 0      0           3 31 Dec  1969 fa2da5bcc17fb2e5c2025c1b76104bdd0f5b9ce64d6d4b29762e58aa11d97ee8/VERSION
-rw-r--r--  0 0      0           0 31 Dec  1969 fa2da5bcc17fb2e5c2025c1b76104bdd0f5b9ce64d6d4b29762e58aa11d97ee8/layer.tar
-rw-r--r--  0 0      0         178 31 Dec  1969 fa2da5bcc17fb2e5c2025c1b76104bdd0f5b9ce64d6d4b29762e58aa11d97ee8/json
-rw-r--r--  0 0      0         115 31 Dec  1969 repositories
-rw-r--r--  0 0      0        1037 31 Dec  1969 manifest.json
```

Here's what happens:
  - [`container-structure-tools`'s `NewTarDriver`](https://github.com/GoogleContainerTools/container-structure-test/blob/6168f990919b24d51fe3b28e6429823c5feb0f32/pkg/drivers/tar_driver.go#L40) uses `container-diff` [`tarball.Image()/ImageFromPath()`](https://github.com/GoogleContainerTools/container-structure-test/blob/6168f990919b24d51fe3b28e6429823c5feb0f32/vendor/github.com/GoogleContainerTools/container-diff/pkg/util/image_utils.go#L84) to load the image.
  - `ImageFromPath` calls into `go-containerregistry` to open the Image, which [checks if the image layers are compressed](https://github.com/GoogleContainerTools/container-structure-test/blob/master/vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go#L80).  This is determined by checking if the top-most layer [`IsGzipped`](https://github.com/GoogleContainerTools/container-structure-test/blob/6168f990919b24d51fe3b28e6429823c5feb0f32/vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go#L144).
  - This [`IsGzipped` call fails](https://github.com/GoogleContainerTools/container-structure-test/blob/6168f990919b24d51fe3b28e6429823c5feb0f32/vendor/github.com/google/go-containerregistry/pkg/v1/v1util/zip.go#L123) as the layer is 0 bytes and so this read returns an EOF which is cascaded up the chain.

**Comment by briandealwis** [comment]
I opened GoogleContainerTools/container-structure-test#197 and did some initial digging.

It turns out that the generated Windows images have 0-byte layer.tar files:
```
$ tar bazel-out/darwin-fastbuild/bin/tests/docker/basic_windows_image.tar 
-rw-r--r--  0 0      0         907 31 Dec  1969 378fb1f1c5d59102b2b942e7c5cd76ce913cb5a4b74e97f87041dc61ab14b21e.json
-rw-r--r--  0 0      0           3 31 Dec  1969 0239ecd27132f0d70c7946a5365ef1f0a3edc7ecf6bdeeb61b4215598beb9828/VERSION
-rw-r--r--  0 0      0       10240 31 Dec  1969 0239ecd27132f0d70c7946a5365ef1f0a3edc7ecf6bdeeb61b4215598beb9828/layer.tar
-rw-r--r--  0 0      0         461 31 Dec  1969 0239ecd27132f0d70c7946a5365ef1f0a3edc7ecf6bdeeb61b4215598beb9828/json
-rw-r--r--  0 0      0           3 31 Dec  1969 54625cd3a0909e177f99d40c983676e65cd2ba5e3231670bd3b3a060463e384c/VERSION
-rw-r--r--  0 0      0           0 31 Dec  1969 54625cd3a0909e177f99d40c983676e65cd2ba5e3231670bd3b3a060463e384c/layer.tar
-rw-r--r--  0 0      0         250 31 Dec  1969 54625cd3a0909e177f99d40c983676e65cd2ba5e3231670bd3b3a060463e384c/json
-rw-r--r--  0 0      0           3 31 Dec  1969 fa2da5bcc17fb2e5c2025c1b76104bdd0f5b9ce64d6d4b29762e58aa11d97ee8/VERSION
-rw-r--r--  0 0      0           0 31 Dec  1969 fa2da5bcc17fb2e5c2025c1b76104bdd0f5b9ce64d6d4b29762e58aa11d97ee8/layer.tar
-rw-r--r--  0 0      0         178 31 Dec  1969 fa2da5bcc17fb2e5c2025c1b76104bdd0f5b9ce64d6d4b29762e58aa11d97ee8/json
-rw-r--r--  0 0      0         115 31 Dec  1969 repositories
-rw-r--r--  0 0      0        1037 31 Dec  1969 manifest.json
```

Here's what happens:
  - [`container-structure-tools`'s `NewTarDriver`](https://github.com/GoogleContainerTools/container-structure-test/blob/6168f990919b24d51fe3b28e6429823c5feb0f32/pkg/drivers/tar_driver.go#L40) uses `container-diff` [`tarball.Image()/ImageFromPath()`](https://github.com/GoogleContainerTools/container-structure-test/blob/6168f990919b24d51fe3b28e6429823c5feb0f32/vendor/github.com/GoogleContainerTools/container-diff/pkg/util/image_utils.go#L84) to load the image.
  - `ImageFromPath` extract the image name from the provided image tar file. This calls into `go-containerregistry` to open the Image, which [checks if the image layers are compressed](https://github.com/GoogleContainerTools/container-structure-test/blob/master/vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go#L80).  This is determined by checking if the top-most layer [`IsGzipped`](https://github.com/GoogleContainerTools/container-structure-test/blob/6168f990919b24d51fe3b28e6429823c5feb0f32/vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go#L144).  This `IsGzipped` call fails as the layer is 0 bytes and so [this read returns an EOF](https://github.com/GoogleContainerTools/container-structure-test/blob/6168f990919b24d51fe3b28e6429823c5feb0f32/vendor/github.com/google/go-containerregistry/pkg/v1/v1util/zip.go#L123) which cascades upwards as a failure.

**Comment by briandealwis** [comment]
So it seems [0-byte layer.tar files are considered valid](https://github.com/moby/moby/pull/18226).
Ah, container-structure-test switched to using [`go-containerregistry`](https://github.com/GoogleContainerTools/container-structure-test/pull/181) in v1.6.0.

I've opened google/go-containerregistry#367

**Comment by briandealwis** [comment]
[container-structure-test v1.8.0](https://github.com/GoogleContainerTools/container-structure-test/releases) has been released, which fixes the odd test failure, and the tests now pass.  PTAL @nlopezgi

**Pull request merged**
