### PR TITLE
v0.3.0 -> v0.4.0

### PR DESCRIPTION
**Pull request by dekkagaijin**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by dekkagaijin** [comment]
@bazel-io Test this please

**Comment by dekkagaijin** [comment]
@mattmoor can you '@bazel-io Test this please' ?

**Comment by mattmoor** [comment]
Great, it looks like you have to amend the commit for buildkite to pick this up...

**Comment by dekkagaijin** [comment]
@mattmoor done w/ smush

**Comment by mattmoor** [comment]
@philwo Not sure why this PR seems to have been lost by buildkite?

**Comment by mattmoor** [comment]
w/e this is a README, I'm just merging it. :)

**Pull request merged**
