### PR TITLE
Fix the root directory when building for Linux on Windows.

### PR DESCRIPTION
**Pull request by faube**
Otherwise, the .tar file gets a weird structure that is not well interpreted in Linux; e.g. files get names like ".\a\b\c\file" (that is a filename, not a path).

### CODE REVIEW

**Comment by faube** [comment]
Please let me know if there is a better way to know if the Bazel host is Windows; I could not find a consistent approach elsewhere in rules_docker.

**Review by smukherj1 — APPROVED** [review]

**Comment by faube** [comment]
> New changes are detected. LGTM label has been removed.

Oops, I may have clicked the wrong button. I was seeing a message saying this branch was out of date with the master.

What is the next step for this Pull Request?

**Review by smukherj1 — APPROVED** [review]

**Review by smukherj1 — APPROVED** [review]

**Pull request merged**
