### PR TITLE
Add Mixpanel as an adopter

### PR DESCRIPTION
**Pull request by andyleap**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [n/a] Tests for the changes have been added (for bug fixes / features)
- [n/a] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
N/A

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]

**Comment by alexeagle** [comment]
I don't think the CLA is meant to cover something like this. It's not source code where the intellectual property matters.
I reauthored the commit to get past CLA bot.

**Comment by alexeagle** [comment]
@googlebot I signed it!

**Comment by alexeagle** [comment]
Wow that's a sad outcome

**Comment by andyleap** [comment]
Totally fine if someone else just wants to add us as an adopter :/

**Pull request closed without merging**
