### PR TITLE
Add a flag to control pushing new tags on unchanged images

### PR DESCRIPTION
**Pull request by zbarahal**
My team ran into a use case where due to Bazel pushing a new tag to ECR for each service every time the monorepo changes we ran into the 100 tag per image cap on ECR for services that don't change often. This is because ECR groups tags onto images by digest so if your image isn't changing but you keep pushing new tags you end up with a bunch of tags on one image.

Per https://github.com/bazelbuild/rules_docker/issues/1106 I added a new flag to the new_push functionality and updated the pusher. I may explore adding this to the old fast pusher as well.

Closes https://github.com/bazelbuild/rules_docker/issues/1106

### CODE REVIEW

**Comment by zbarahal** [comment]
@smukherj1 Integration tests are added and CI is passing. The PR suggests adding @alex1545 as a reviewer but since we have been discussing it should you be the reviewer? Either way is fine by me but this is ready for review now.

Still working on the CLA but we'll have that done soon.

**Comment by zbarahal** [comment]
There are also a lot of CI builds attached to this PR and I'm not sure which are required. Travis is passing and I've cleaned up the formatting for buildifier. Let me know if other CIs are failing that are required.

**Comment by zbarahal** [comment]
@googlebot I signed it!

**Comment by smukherj1** [comment]
@googlebot rescan

**Comment by zbarahal** [comment]
Thanks @smukherj1!

**Pull request merged**
