### PR TITLE
Run push commands in push-all in parallel

### PR DESCRIPTION
**Pull request by ains**
Simple PR to perform push-all in parallel.
Not super stoked about more reliance on bash (is there a better way to to this that means there's no bash usage? maybe building a bin for multi pushing or updating `google/containerregistry` to accept multiple images).

However this works for now and reduces push time for ~25 (unchanged) images from ~45 seconds to ~3 seconds.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by mattmoor** [comment]
Please test this (for Bazel bot)

**Comment by mattmoor** [comment]
Test this please

**Comment by mattmoor** [comment]
@ains Ack on the bash.  I might revisit this rule to sit at the core of the push logic for `rules_k8s`.  My prototype version of those forks the pusher (for expediency) and suffers this same problem for multiple images.

**Comment by mattmoor** [comment]
Thanks for the change, looks good.

**Comment by mattmoor** [comment]
@ixdy FYI

**Pull request merged**
