### PR TITLE
Update run.bzl

### PR DESCRIPTION
**Pull request by dieend**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
Rules now accept extra dependency

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by dieend** [comment]
@googlebot I signed it!

**Review by alexeagle — APPROVED** [review]

**Comment by sluongng** [comment]
I am a bit confused with this PR: there is a clear lack of context in the PR description and the commit messages are also lacking in term of quality.

I would suggest at minimum linking PR with an issue stating the problem?

**Comment by alexeagle** [comment]
@sluongng I agree, this is one of those no-time-for-maintainership issues where the code change is pretty clear but everything else about the PR needs work. I can choose between merging it or teaching the contributor, but probably not both

**Comment by alexeagle** [comment]
sorry I was a bit defensive there. Thanks for pointing this out @sluongng - next time I won't be so permissive with merging.

**Comment by sluongng** [comment]
@alexeagle all is good. I know it takes a lot of effort being a maintainer and I know many bazelbuild projects are still in an early stage, process may be unclear. 

There will always be a tradeoff between maintainability and speed but I have no clue where to draw the line for these projects.

I usually have to read HEAD of 'master/main' branch of these projects to find whether they are suitable to update our internal tracking. When a PR comes with unclear context, it might takes a bit of extra time and effort to digest.

Thanks for keeping the project fresh 🤝

**Comment by alexeagle** [comment]
I updated the original comment to reflect my understanding of the issue, so at least anyone arriving here from release notes or commit history can understand it better.

**Comment by dieend** [comment]
Sorry for not providing enough context. I was planning to update the PR description after further testing internally and didn't expect it's merged pretty soon.

Thank you for improving the PR description 🙏

**Pull request merged**
