### PR TITLE
Fast pulls and pushes

### PR DESCRIPTION
**Pull request by mattmoor**
This is a work in progress on top of https://github.com/bazelbuild/rules_docker/pull/70 building tighter integration between `docker_pull`, `docker_push` and the new intermediate form of `docker_build` in the diffbase PR.

Right now this just consists of a `docker_import` rule, which will be useful for folks checking in base images to a mono-repo to still get performant builds.  It will also be an implementation detail of `docker_pull` in a subsequent change.

For now, I'm simply opening this PR to run CI over my branch :)

### CODE REVIEW

**Comment by mattmoor** [comment]
@damienmg @dlorenc I'll do the remainder of the work in this branch, but I'm going to checkpoint pieces of it.  If you want a more complete picture of where things are headed, watch this PR. :)

**Comment by mattmoor** [comment]
The remaining changes need some changes in `google/containerregistry`, which are out for internal review.  I'll post the `docker_pull` and `docker_push` changes here once I can update the `google/containerregistry` version to pull in a new release with the changes we need.

**Comment by mattmoor** [comment]
The `google/containerregistry` [changes](https://github.com/google/containerregistry/commit/9eebd302682299135ba2ae03866e17fba96ec2f0) are in, I'll cut a release once Travis comes back happy.

**Comment by mattmoor** [comment]
Ok, this PR should contain the full set of changes now.

**Comment by mattmoor** [comment]
Note to self, update docs to drop `:image.tar` everywhere.

**Comment by jmillikin-stripe** [comment]
> This is a work in progress on top of #70 building tighter integration between docker_pull, docker_push and the new intermediate form of docker_build in the diffbase PR.

For users that want to build and transport Docker images without running a Linux-only daemon as root, the Bazel docker rules and `pusher.par` are currently the only game in town. Rather than treating this new image layout as an opaque implementation detail of `docker_push`, consider naming it and documenting its structure.

Then you'd have the additional advantage over `docker save` and `docker push` in that people could figure out how to integrate other tooling into the pipeline without having to crack open the Docker CLI source code.

**Comment by mattmoor** [comment]
@jmillikin-stripe Not *exactly* the intent of the intermediate format, but I definitely acknowledge the broader sentiment.  I will open an issue to track documenting the format on-disk, as well as the intermediate representation in this repo.

**Comment by mattmoor** [comment]
@damienmg @dlorenc This should just be a handful of changes now and should be RFAL.

**Comment by mattmoor** [comment]
@dlorenc Anything to add?

**Pull request merged**
