### PR TITLE
Groovy sandwich

### PR DESCRIPTION
**Pull request by mattmoor**
Add fine-layering support to `rules_groovy`.

This is based on my PR that does that same for `rules_scala`.

### CODE REVIEW

**Comment by damienmg** [comment]
Sandwich on java kind so irina :)

**Comment by mattmoor** [comment]
Ok, the diffbase is merged and this rebased, so RFAL.

**Comment by mattmoor** [comment]
@iirina Any chance you can TAL?  I'd like to land this before I go on holiday.

**Comment by mattmoor** [comment]
@iirina @damienmg ping

**Comment by mattmoor** [comment]
Right now all of the `lang_image` rules live here (for better or for worse), but tl;dr I'd love for the language rule owners to take over some measure of ownership (and of the distroless reference runtimes).

As some background, you can think of `container_image` as a universal replacement for our internal package format and the mono-archives that Blaze traditionally produces (e.g. PAR, deploy-JAR, SAR, ...).  However, in addition to bundling all of the `runfiles` together we also ~link it against a base Docker image containing a reference implementation of the target environment (e.g. JRE, Python interpreter, glibc, ...).

With `lang_image` the aim is to produce a (largely) drop-in replacement for `lang_binary` rules that instead of producing a mono-archive, produce a Docker image.  In cases like Python, JRE languages and (hopefully today) Node.js we can take better advantage of the Docker image format and separate out unchanging elements into their own layers to speed up developer iteration (if it doesn't change then you avoid repushing/repulling and get significantly faster redeployments, on the order of 99% less push/pull).

I hadn't fully take advantage of the layering aspects of this in Scala (until recently) and Groovy (until this PR).  It turned out that the same thing blocking my initial super-naive attempt at layering was the same problem as JRE-languages face trying to use each others libraries

The bulk of this change involves inlining `groovy_binary` for two reasons (IIRC):
1. The `//external:groovy` dependency isn't properly added to `runfiles` (again IIRC, this is fixable upstream)
1. We want `//external:groovy` in its own layer (not fixable upstream)

**Comment by mattmoor** [comment]
@iirina Did I answer your question?  Anything else I can speak to?

**Comment by mattmoor** [comment]
@iirina Ping :)

**Comment by iirina** [comment]
@mattmoor I'm so sorry, all my emails from rules_docker were filtered away :( Thanks for the explanation.

**Pull request merged**
