### PR TITLE
Fix buildifier formatting errors

### PR DESCRIPTION
**Pull request by nimerritt**

### CODE REVIEW

**Comment by nimerritt** [comment]
@erain Formatting in separate PR as requested :)

**Comment by tejal29** [comment]
@bazel-io please test this.

**Comment by tejal29** [comment]
Jenkins test this please

**Comment by tejal29** [comment]
@bazel-io test this please

**Comment by erain** [comment]
I've already enabled the bazel tests. 

@tejal29 Thanks for looking into this. It looks we need to approve tests in the bazel ci page

**Pull request merged**
