### PR TITLE
propagate tags to py3_image layers

### PR DESCRIPTION
**Pull request by vsbus**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
We are using `py3_image()` with `layers` parameter in one of our projects. These images have `tags = ["manual"]` so we don't expect them to build with `bazel build //...`. However, we observing that `.tar` files with layers are still built. That happened because tags were not propagated to the layer's targets. This PR is trying to fix the issue.

Issue Number: N/A

## What is the new behavior?
`bazel build //...` doesn't build extra targets like layers when manual tag is used.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vsbus** [comment]
It would be great to add a test for this change but I am not very familiar with the project yet. If there is an easy way to do it I will appreciate directions to add such a test.

**Comment by vsbus** [comment]
@googlebot I signed it!

**Comment by vsbus** [comment]
Hey @pcj , it i s my first PR in this project so I am not sure how to request code review properly. I saw you approved one of recent PRs so thought you might be able to have a look at this one. Thanks!

**Review by stepango — APPROVED** [review]

**Comment by gravypod** [comment]
Hey @vsbus, thank you for contributing this change! I was wondering if you'd be able to expand this CL to the remaining image rules that have this same issue. Here's a list of the places:

1. [cc](https://github.com/bazelbuild/rules_docker/blob/master/cc/image.bzl#L87-L93)
2. [d](https://github.com/bazelbuild/rules_docker/blob/master/d/image.bzl#L56-L62)
3. [go](https://github.com/bazelbuild/rules_docker/blob/master/go/image.bzl#L115-L120)
4. [groovy](https://github.com/bazelbuild/rules_docker/blob/master/groovy/image.bzl#L75-L82)
5. [java](https://github.com/bazelbuild/rules_docker/blob/master/java/image.bzl#L423-L429)
6. [kotlin](https://github.com/bazelbuild/rules_docker/blob/master/kotlin/image.bzl#L74-L81)
7. [python](https://github.com/bazelbuild/rules_docker/blob/master/python/image.bzl#L110-L115)
8. [python3](https://github.com/bazelbuild/rules_docker/blob/master/python3/image.bzl#L105-L111)
9. [rust](https://github.com/bazelbuild/rules_docker/blob/master/rust/image.bzl#L57-L62)

These all have the same issue and we've received some requests to fix this/[similar patches](https://github.com/bazelbuild/rules_docker/pull/1730) it seems. It would be amazing to get a single patch in that resolves these issues for all languages.

**Comment by vsbus** [comment]
Hey @gravypod, absolutely! I walked through all the languages and applied the same change everywhere. Please take a look.

**Review by gravypod — CHANGES_REQUESTED** [review]
Looks great. We just need to find out why CI is failing. Could you please:

1. Rename this PR to something that isn't py3_* specific
2. Rebase this

Hopefully whatever is breaking CI is something that's already fixed in master.

**Comment by vsbus** [comment]
I've messed up with this PR, fork and rebasing, will close this PR and create a new one.

**Comment by vsbus** [comment]
here is a clean PR with updated title https://github.com/bazelbuild/rules_docker/pull/1836

**Pull request closed without merging**
