### PR TITLE
Remove accidentally commited file.

### PR DESCRIPTION
**Pull request by dlorenc**
Ref #30 

I created this accidentally while debugging some of the tests. It never should have been committed.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by mattmoor** [comment]
test this please

**Comment by mattmoor** [comment]
The way GH displays diffs I totally missed that :(

**Comment by dlorenc** [comment]
> The way GH displays diffs I totally missed that :(

Yeah it makes it a little hard to see exactly what got changed :(

**Pull request merged**
