### PR TITLE
Revert to using gflags but use it from a pips package instead of Bazel Tools

### PR DESCRIPTION
**Pull request by smukherj1**
Next version of Bazel is expected to stop providing gflags via Bazel tools according to #1533

### CODE REVIEW

**Comment by mmorearty** [comment]
@smukherj1 should `container_repositories()` be updated to load `pip_deps`?

The way things are now, after this change, my own project gets errors like this:

```
ERROR: .../BUILD:45:12: every rule of type container_image_ implicitly depends upon the target '@io_bazel_rules_docker//container:build_tar', but this target could not be found because of: error loading package '@io_bazel_rules_docker//container': Unable to find package for @pip_deps//:requirements.bzl: The repository '@pip_deps' could not be resolved.
```

**Comment by smukherj1** [comment]
> @smukherj1 should `container_repositories()` be updated to load `pip_deps`?
> 
> The way things are now, after this change, my own project gets errors like this:
> 
> ```
> ERROR: .../BUILD:45:12: every rule of type container_image_ implicitly depends upon the target '@io_bazel_rules_docker//container:build_tar', but this target could not be found because of: error loading package '@io_bazel_rules_docker//container': Unable to find package for @pip_deps//:requirements.bzl: The repository '@pip_deps' could not be resolved.
> ```

@mmorearty Due to a quirk of how Bazel works, `container_repositories()` can't be updated to run `pip_deps` because `load` statements in Bazel can only be defined at the top level and the `pip_deps()` isn't defined until the `container_repositories()` macro executes. Instead, consider updating your WORKSPACE to do the following additional step from rules_docker's [setup](https://github.com/bazelbuild/rules_docker#setup)

```
load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()
```

**Comment by mmorearty** [comment]
Ah, thanks! I didn't notice that `container_repositories()` and `container_deps()` were separate things, and sure enough my repo was missing the call to `container_deps()`.

**Comment by whilp** [comment]
See related report in https://github.com/bazelbuild/rules_docker/pull/1535

**Comment by alexeagle** [comment]
@smukherj1 Hey, I think this should have qualified as a breaking change and not rolled out in a patch release. This broke rules_nodejs examples as well, and I don't think these users should need to change their code (WORKSPACE) to accomodate some internal implementation detail released as a bugfix. Should have been a 0.15.
Do you have tests in rules_docker than told you this was a breaking change? I've been adding such integration tests (like recently to rules_python) and would be happy to help.
Also rather than using pip, how about just distributing the couple of needed .whl files vendored into your distro, so you don't introduce a tangle of WORKSPACE dependencies? Ideally IMO a core ruleset like docker should have ~0 dependencies.

**Pull request merged**
