### PR TITLE
Update for python 3 compatibility

### PR DESCRIPTION
**Pull request by hwright**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by hwright** [comment]
Looks like this managed to trigger a NPE in Bazel. :(

I *think* it is related to bazelbuild/bazel#4173, which looks to be fixed in HEAD.  I'm not sure how that impacts the CI runner.

**Comment by mattmoor** [comment]
Yeah, we're waiting on a patch release and/or 0.9 :(

**Comment by mattmoor** [comment]
Although they claim it is cut, so not sure why this hasn't been picked up...

**Comment by hwright** [comment]
Yeah, I haven't seen a release discussion on `bazel-dev` or `bazel-discuss` :(

From the announcement mail to `bazel-discuss`, it appears that the NPE fix is in 0.8.1, which is currently in rc: https://releases.bazel.build/0.8.1/rc3/index.html

**Comment by mattmoor** [comment]
Ah, yeah sorry I was misinterpreting [this](https://github.com/bazelbuild/bazel/issues/4206) comment.

**Comment by hwright** [comment]
@mattmoor 0.8.1 has been released, which presumably fixes our NPE.  How long before you think it's on the CI machines?

**Comment by mattmoor** [comment]
I'm trying to canary it on a PR right now.  Once it comes back I'll start retriggering everything.

**Comment by mattmoor** [comment]
Twiddling for CI

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by mattmoor** [comment]
Test this please

**Comment by mattmoor** [comment]
Thanks for your patience and PR @hwright

**Pull request merged**
